### ISSUE TITLE
Webpack 4.x Mangling issue

### ISSUE THREAD

**Issue by Apidcloud** [webpack-contrib/uglifyjs-webpack-plugin#234]
Good evening!

I'm trying to use `webpack 4.x` with `uglifyjs` plugin, but I need to _disable mangling_, which seems to not be working as before. Using **v1.1.8** with `webpack 3.11` **didn't change class names** when `mangle` was set to `false`; but it is changing them with `webpack 4.x`.

The version of the underlying `uglify-es` in `node_modules` is **3.3.9** in both cases.

What could be the issue?

Here's part of `webpack.config`:
```javascript
mode: "production",
  optimization: {
    minimizer: [
      new UglifyJSPlugin({
        uglifyOptions: {
          beautify: false,
          compress: true,
          comments: false,
          mangle: false,
          toplevel: false,
          keep_classnames: true, // <-- doesn't exist, I guess. It's in harmony branch
          keep_fnames: true //
        }
      })
    ]
  },
```

Thanks!

Edit: Just to make sure, cleaning yarn's cache didn't help either.

**Comment by Apidcloud** [comment]
Updating to 1.2.0 doesn't seem to work either.

Still get stuff like `class gameObject_GameObject` instead of `class GameObject`.
The only changes are literally webpack 3.x (3.6 and 3.11) to webpack 4.x and changing the uglify configs from `plugins` to with webpack's config as shown above.

The options are the same, and yet the output differs (at least in class names, for some reason):
```javascript
new UglifyJSPlugin({
        uglifyOptions: {
          warning: "verbose",
          ecma: 6,
          beautify: false,
          compress: false,
          comments: false,
          mangle: false,
          toplevel: false,
          keep_classnames: true,
          keep_fnames: true
        }
      })
```

It's really late here (4:40am), so for now I can only reference the repository branches:
https://github.com/scarlettgamestudio/scarlett-framework/tree/editor-issue-3 uses webpack 3.6 and sets `uglifyjs 1.1.8` `mangle` to `false`, resulting in **no changes in class names**.

https://github.com/scarlettgamestudio/scarlett-framework/tree/pr/webpackV4 uses webpack 4.x, and sets `uglifyjs 1.2.0` (tested with `1.1.8` as well) `mangle` to `false` and `keep_classnames` to `true`, but it **changes class names**.

If you have the time to test it, run `yarn` and then `yarn build:deploy:editor`
It should produce a build in `builds/dist/scarlett.framework.min.js`, where **class names are renamed** (and __I don't want to__).
search for `class gameObject` and you'll see that it produced `class gameObject_GameObject` instead of `class GameObject`.

**Comment by sokra** [comment]
Could you try with `optimization.minimize: false` and add the plugin to `plugins` directly? I want to figure out if this is a webpack or uglifyjs-webpack-plugin issue.

**Comment by sokra** [comment]
Could this file be the problem: https://github.com/scarlettgamestudio/scarlett-framework/blob/pr/webpackV4/config/addons/webpack.uglifyes6.js

**Comment by Apidcloud** [comment]
Just tried, but the result is the same. I'll try to create a smaller test case.

That file is only used with the webpack 3.x branch via the env variable in the script.

Thanks!

**Comment by Apidcloud** [comment]
Was able to reproduce the issue within a __way smaller__ repository: https://github.com/Apidcloud/scarlett-blast

I basically mirrored what's happening on the other one (see `demo/src` - it only contains 2 classes now, namely Logger and Game).
After running `yarn build`, the class `Logger` is fine, but class `Game` appears as `class game_Game`.

I'll keep investigating 😄

**Comment by Apidcloud** [comment]
You're welcome 😄 

I've branched out the issue so you can keep testing in the same repository: https://github.com/Apidcloud/scarlett-blast/tree/issueWebpack

**Comment by kzc** [comment]
> Still get stuff like class `gameObject_GameObject` instead of class `GameObject`

It's most likely a webpack 4 module hoisting and/or export renaming issue from the description. I'm not going to build either project, but you can verify it by disabling uglify and searching the resultant webpack output for `gameObject_GameObject`.

See also:

https://github.com/webpack/webpack/issues/5463#issuecomment-321186248
https://github.com/webpack/webpack/issues/5463#issuecomment-321247575

By the way, I don't follow the uglify project any longer. If you think it's an uglify issue submit a bug report to that project with a self contained JS input file with no third party tools/libraries/webpack involved.

**Comment by Apidcloud** [comment]
In one of my latest replies, I mentioned that I don't think it's an uglify js issue, as it works well with webpack 3.x, but it doesn't with webpack 4.x 'production' mode. But I only found out that 2 days ago and thus creating the issue here.

Also, that's precisely why I linked https://github.com/Apidcloud/scarlett-blast/tree/issueWebpack 

There are no third party tools or libraries involved in there. Classes have nothing inside.

**Comment by kzc** [comment]
> Could you try with optimization.minimize: false and add the plugin to plugins directly? I want to figure out if this is a webpack or uglifyjs-webpack-plugin issue.

Set `optimization.minimize: false` and **remove** the uglify plugin from the webpack config file altogether. If `gameObject_GameObject` or `game_Game` is in the webpack output, then it's a webpack issue.

**Comment by kontrollanten** [comment]
I'm also experiencing problem with passing `uglifyOptions` in Webpack 4. I tried the following:

```
optimization: {
  minimizer: [
    new UglifyJSPlugin({
      uglifyOptions: { ... },
    }),
  ],
},
```

But I get
```
Error: webpack.optimize.UglifyJsPlugin has been removed, please use config.optimization.minimize instead
```
from Webpack.

I though that the options should be sent to `optimization.minimize`, but it only takes a boolean. Does anyone have a clue about where to configure UglifyJSPlugin in Webpack 4?

**Comment by michael-ciniawsky** [comment]
@kontrollanten Are you requiring it from  `const { UglifyJSPlugin }  = require('webpack').optimize` ?

**Comment by kontrollanten** [comment]
No, I tried that now though. But then I get

```
TypeError: UglifyJSPlugin is not a constructor
```

And when try without `new`, I'll get

```
TypeError: UglifyJSPlugin is not a function
```

**Comment by michael-ciniawsky** [comment]
Please show the relevant part of your `webpack.config.js` :)

**Comment by michael-ciniawsky** [comment]
````js
const UglifyJSPlugin = require('uglifyjs-webpack-plugin')

...
optimization: {
  minimizer: [
    new UglifyJSPlugin({
      uglifyOptions: { ... },
    }),
  ],
},
```

Doesn't work ?

**Comment by kontrollanten** [comment]
It seems that the following is working. The exception was thrown through [offline-plugin](https://github.com/NekR/offline-plugin). 

```
const UglifyJSPlugin = require('uglifyjs-webpack-plugin');

...

  optimization: {
    minimizer: [
      new UglifyJSPlugin({
        uglifyOptions: {
          output: {
            comments: false
          },
          compress: {
            unsafe_comps: true,
            properties: true,
            keep_fargs: false,
            pure_getters: true,
            collapse_vars: true,
            unsafe: true,
            warnings: false,
            screw_ie8: true,
            sequences: true,
            dead_code: true,
            drop_debugger: true,
            comparisons: true,
            conditionals: true,
            evaluate: true,
            booleans: true,
            loops: true,
            unused: true,
            hoist_funs: true,
            if_return: true,
            join_vars: true,
            cascade: true,
            drop_console: true
          }
        }
      }),
    ]
  },
```

Now I have a lot of other errors thrown from other plugins. The investigation continues. Thanks for your quick response and a great plugin!

**Comment by ketabi** [comment]
Look at:
https://stackoverflow.com/a/49767690/6200607
for more information.

**Comment by cihati** [comment]
I needed to upgrade offline-plugin -- a relevant issue was fixed at 5.0.3 I believe.

**Comment by valera1401** [comment]
Why this issue is closed ? The problem still exists. Mangle can't be disabled.

**Comment by gmfun** [comment]
@sokra Seems to be problem with webpack, because `minimize: false` is also changing the class name. Facing this issue with webpack@4.16.2

**Comment by kindofone** [comment]
I installed [**uglifyjs-3-webpack-plugin**](https://github.com/whtsky/uglifyjs-3-webpack-plugin):
```
npm i -D uglifyjs-3-webpack-plugin
```

Required it in my `webpack.config.js` instead of the built-in uglifyjs-webpack-plugin:
```JavaScript
const UglifyJsPlugin = require("uglifyjs-3-webpack-plugin");
```

Now `mangle: false` is working again! 🎉

**Comment by KevinBrogan** [comment]
guys, i found the solution.

 	optimization:
	{
		concatenateModules: false
	}

If that is turned on, you end up with classes that are named class_Class and class_OtherClass

Minimization is still an issue if you need the class names, but that can be fixed by using the minimizer options.

Default production webpack 4 config for me is now:

	mode: 'production',
 	optimization:
	{
		concatenateModules: false,
		minimizer:
		[
			new TerserPlugin
			(
				{
					terserOptions:
					{
						keep_classnames: true
					}
				}
			)
		]
	}
